# Generated by Django 3.2.2 on 2021-12-11 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('days', models.IntegerField(choices=[(24, 24), (25, 25)], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift', models.CharField(choices=[('1', 'Image'), ('2', 'Video'), ('3', 'Quote')], default='1', max_length=254)),
                ('date', models.IntegerField()),
                ('content', models.TextField(max_length=254, unique=True)),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='dates.calendar')),
            ],
            options={
                'verbose_name_plural': 'Dates',
            },
        ),
    ]
