# Generated by Django 4.0 on 2021-12-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
